"""empty message

Revision ID: 0319a73cca46
Revises: None
Create Date: 2016-05-08 14:12:47.637092

"""

# revision identifiers, used by Alembic.
revision = '0319a73cca46'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive', sa.Column('modifiedBy', sa.String(length=3), nullable=True))
    op.add_column('luggage', sa.Column('modifiedBy', sa.String(length=3), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('luggage', 'modifiedBy')
    op.drop_column('archive', 'modifiedBy')
    ### end Alembic commands ###
