"""empty message

Revision ID: 294e7c495809
Revises: eea014d0d625
Create Date: 2016-05-20 20:40:49.517790

"""

# revision identifiers, used by Alembic.
revision = '294e7c495809'
down_revision = 'eea014d0d625'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archive', 'location',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=20),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text(u"''"))
    op.alter_column('luggage', 'location',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=11),
               type_=sa.String(length=255),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('luggage', 'location',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=11),
               existing_nullable=True)
    op.alter_column('archive', 'location',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=20),
               existing_nullable=True,
               existing_server_default=sa.text(u"''"))
    ### end Alembic commands ###
