"""empty message

Revision ID: ccd3f4d7ea94
Revises: 294e7c495809
Create Date: 2017-02-22 21:13:18.406172

"""

# revision identifiers, used by Alembic.
revision = 'ccd3f4d7ea94'
down_revision = '294e7c495809'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column(u'archive', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'archive', 'hotel', ['hotel_id'], ['id'])
    op.add_column(u'luggage', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'luggage', 'hotel', ['hotel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'luggage', type_='foreignkey')
    op.drop_column(u'luggage', 'hotel_id')
    op.drop_constraint(None, 'archive', type_='foreignkey')
    op.drop_column(u'archive', 'hotel_id')
    op.drop_table('user')
    op.drop_table('hotel')
    # ### end Alembic commands ###
