"""empty message

Revision ID: e7860c0dc119
Revises: ccd3f4d7ea94
Create Date: 2017-02-23 18:33:57.126085

"""

# revision identifiers, used by Alembic.
revision = 'e7860c0dc119'
down_revision = 'ccd3f4d7ea94'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('image', sa.String(length=150), nullable=True))
    op.alter_column('user', 'authenticated',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'authenticated',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('hotel', 'image')
    # ### end Alembic commands ###
