"""empty message

Revision ID: eea014d0d625
Revises: 0319a73cca46
Create Date: 2016-05-13 21:55:48.484027

"""

# revision identifiers, used by Alembic.
revision = 'eea014d0d625'
down_revision = '0319a73cca46'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archive', sa.Column('lastModified', sa.DateTime(), nullable=True))
    op.alter_column('archive', 'timeIn',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('archive', 'timeOut',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('luggage', sa.Column('lastModified', sa.DateTime(), nullable=True))

    op.alter_column('luggage', 'timeIn',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.drop_column('luggage', 'loggedOutBy')
    op.drop_column('luggage', 'timeOut')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('luggage', sa.Column('timeOut', mysql.TIMESTAMP(), server_default=sa.text(u"'0000-00-00 00:00:00'"), nullable=False))
    op.add_column('luggage', sa.Column('loggedOutBy', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=3), nullable=True))
    op.alter_column('luggage', 'timeIn',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text(u'CURRENT_TIMESTAMP'))
    op.drop_column('luggage', 'lastModified')
    op.alter_column('archive', 'timeOut',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('archive', 'timeIn',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('archive', 'lastModified')
    ### end Alembic commands ###
