"""empty message

Revision ID: f128be76490d
Revises: e7860c0dc119
Create Date: 2017-06-30 18:17:26.860243

"""

# revision identifiers, used by Alembic.
revision = 'f128be76490d'
down_revision = 'e7860c0dc119'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('user', 'authenticated',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'authenticated',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
